config/routes.rb
Andrew90Proj1::Application.routes.draw do
  
  get '/sites/new' => "sites#new", :as=> :new_sites
  post '/sites' => "sites#visit"
  get '/sites' => "sites#index", :as=> :index_sites
  get '/sites/:id' => "sites#show", :as=> :show_sites
  get '/sites/:id/pages/:num' => "page#show", :as=> :show_page
  
  match '/sites' => "sites#resource_preflight", :constraints => { :method => "OPTIONS" }
  

end

app/models/page.rb
class Page < ActiveRecord::Base

  /
	self.URL : Page URL (subpath for the page) for this site object
	self.visit_counts : Count for the number of visits to the page
	self.duration : Total duration spent by the users on the page
  /

  attr_accessible :URL, :duration, :visit_counts
  has_many :visits
  belongs_to :site, :foreign_key => :site_id
  
  /
	This method will set the attributes of the Page object with the values passed in by POST request from the client side.
	@modifies self.visit_counts, self.URL, self.duration
	@requires enter_time!=nil & leave_time!=nil & self.visit_counts >= 0
  /
  
  def setValues(url,enter_time,leave_time)
	self.URL=url
	self.duration=self.duration+leave_time-enter_time
	self.visit_counts=self.visit_counts+1
	self.save
  end
  
end

app/models/site.rb
class Site < ActiveRecord::Base
  
  /
	self.url : Site URL for this site object
	self.visit_counts : Count for the number of visits
	self.duration : Total duration spent by the users on the site
  /
  attr_accessible :url, :visit_counts, :duration
  #A Site object has many Visit objects
  has_many :pages

  /
	This method will set the attributes of the Site object with the values passed in by POST request from the client side.
	@modifies self.visit_counts, self.url, self.duration
	@requires enter_time!=nil & leave_time!=nil & self.visit_counts >= 0
  /
  def setValues(url,enter_time,leave_time)
    self.visit_counts=self.visit_counts+1
	self.url=url
	self.duration=self.duration+leave_time-enter_time
	self.save
  end

 end

app/models/visit.rb
class Visit < ActiveRecord::Base
  
  
  /
	self.url : Site URL for the site object associated with the visit object.
	self.duration : Duration for each visit
	self.enter_time : Timestamp for when the visit was initiated.
	self.leave_time : Timestamp for when the visit was terminated.
	site_id : Foreign key for associating a Site object with multiple Visit objects
  /
  attr_accessible :url, :duration, :enter_time, :leave_time
  
  #Visit objects belong to a specific site object
  belongs_to :page, :foreign_key => :page_id
  
/
	This method will set the attributes of the Visit object with the values passed in by POST request from the client side.
	@modifies  self.url, self.duration, self.enter_time, self.leave_time
	@requires enter_time!=nil & leave_time!=nil
  /  
  def setValues(url,enter_time,leave_time)
	self.url=url
	self.duration=leave_time-enter_time
	self.enter_time=enter_time
	self.leave_time=leave_time
	self.save
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/page_controller.rb
class PageController < ApplicationController

  /
	This method, by rendering the show html page, will display all the visit objects and their detials for the specific page. 
  /
  # GET /sites/:id/pages/:num
  def show
    @page = Page.find(params[:num])
    @visits=@page.visits.all
  end
  
end

app/controllers/sites_controller.rb
class SitesController < ApplicationController

  /
	This method sets header for the request that will be sent in response to the CORS request from the client.
	Basically, this will allow access from any site who request CORS request with HTTP POST, GET, or OPTIONS request. 
  /
  def set_cors_headers
	headers["Access-Control-Allow-Origin"] = "*"
	headers["Access-Control-Allow-Methods"] = "POST, GET, OPTIONS"
	headers["Access-Control-Allow-Headers"] = "Content-Type, Origin, Referer, User-Agent"
	headers["Access-Control-Max-Age"] = "3600"
  end

  /
	This method sends the response to the CORS preflight request
  /
  def resource_preflight
	set_cors_headers
	render :text => "", :content_type => "text/plain"
  end

  /
	When the client sends POST request with values for the site URL, entering time, and leaving time,
	this method will process the request and set values for each of the corresponding attribute in the site object,the page object, and the visit object.
	
	Note that the id is already provided in the snippet, so the controller will look up the existing Site object with its id.
	Page objects will be first searched by its URL to check the existence; if it doesn't exist, new page object will be created
	Visit objects will be created everytime a user visits the site.
  /
  # POST /sites
  def visit
    set_cors_headers
    render :text => "OK here is your restricted resource!"
	
	@site = Site.find(params[:id])
	@site.setValues(params[:siteURL],(params[:enter_time]).to_i,(params[:leave_time]).to_i)

	@page=@site.pages.find_or_create_by_URL(:URL=>params[:sitePath])
	@page.setValues(params[:sitePath],(params[:enter_time]).to_i,(params[:leave_time]).to_i)

	@visit = @page.visits.build
	@visit.setValues(params[:sitePath],(params[:enter_time]).to_i,(params[:leave_time]).to_i)
  end

  /
	This method will enable listing of all the sites tracked.
  /
  # GET /sites
  def index
    @sites = Site.all
  end
  
  /
	This method will show all the visit objects corresponding to the Site object identified by the id
  /
  # GET /sites/:id
  def show
    @site = Site.find(params[:id])
    @pages=@site.pages.all
  end
  
  /
	This method will generate a new Site object with its unique id.
	The html page will display the JavaScript snippet with the unique id for the user to insert into their own websites.
  /
  # GET /sites/new
  def new
    @site = Site.new
    @site.save
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/helpers/sites_helper.rb
module SitesHelper
end

app/helpers/visits_helper.rb
module VisitsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Andrew90Proj1</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/page/show.html.erb
<h2> Details on "<%= @page.site.url+@page.URL %>" </h2>

<h3> total duration : <%= @page.duration %> <br> total visits: <%= @page.visit_counts %> </h3><br>

<table border="1" cellspacing="3">
  <tr>
    <th>Visit ID</th>
	<th>Visit Path</th>
	<th>Duration(s)</th>
	<th>Enter time</th>
	<th>Leave time</th>
  </tr>

<% @visits.each do |visit| %>
   <tr>
    <td align='center'><%= visit.id %></td>
	<td align='center'><%= visit.url %></td>
    <td align='center'><%= visit.duration %></td>
	<td><%= Time.at(visit.enter_time) %></td>
	<td><%= Time.at(visit.leave_time) %></td>
  </tr>
<% end %>
</table><br>

<%= link_to("Back",:controller=>'sites',:action=>'show',:id=>@page.site_id) %>

app/views/sites/index.html.erb
<h2>Welcome to Andrew's Analytics Website!!</h2>

<h4><%= link_to 'If you are new to the Analytics service, Click Here!!', new_sites_path %> <br><br>

<table border="1" cellspacing="3">
  <tr>
    <th>ID</th>
	<th>SiteURL</th>
    <th>Visit Count</th>
	<th>Duration(s)</th>
	<th>Average Duration(s)</th>
  </tr>

<% @sites.each do |site| %>
<% if site.visit_counts != 0 %>
  <tr>
    <td><%= site.id %></td>
    <td><%= site.url %></td>
	<td align='center'><%= site.visit_counts %></td>
	<td align='center'><%= site.duration %></td>
	<td align='center'><%= site.duration/site.visit_counts %></td>
	<td><%= link_to "Details", show_sites_path(site) %></td>
  </tr>
<% end %>
<% end %>
</table>

<br />

app/views/sites/new.html.erb
<h2><p>Your site id is: <%= @site.id %> </p></h2>

<h3>Copy and Paste the JavaScript snippet between &lt;head&gt; , &lt;/head&gt; tag </h3><br><br>

&lt;script type="text/javascript"&gt;<br><br>
  
	var enter_time = new Date().getTime()/1000;<br><br>
 
	window.onunload=sendPOSTInfo;<br><br>
	
	function sendPOSTInfo(){<br>
		var xhr = new XMLHttpRequest();<br>
		xhr.open('POST',"http://vast-plateau-9627.herokuapp.com/sites" , false);<br>
		var siteURL = window.location.protocol + "//" + window.location.host;<br>
		var sitePath = window.location.pathname;<br>
		var id = <%= @site.id %><br>
		var leave_time = new Date().getTime()/1000;<br>
		var params ="id="+id+"&"+"siteURL="+siteURL+"&"+"sitePath="+sitePath+"&"+"enter_time="+enter_time+"&"+"leave_time="+leave_time;<br>  
		xhr.setRequestHeader("Content-type", "application/x-www-form-urlencoded");<br>
		xhr.send(params);<br>
	}<br>
&lt;/script&gt;
<br><br>
<%= link_to "Back", index_sites_path %> 
 

app/views/sites/show.html.erb
<h2> Details on "<%= @site.url %>"</h2>

<h3> total duration : <%= @site.duration %> <br> total visits: <%= @site.visit_counts %> </h3><br>


<table border="1" cellspacing="3">
  <tr>
	<th>Page ID</th>
	<th>Page Path</th>
	<th>Visit Count</th>
	<th>Duration(s)</th>
  </tr>

<% @pages.each do |page| %>
   <tr>
	<td align='center'><%= page.id %></td>
    <td align='center'><%= page.URL %></td>
	<td align='center'><%= page.visit_counts %></td>
    <td align='center'><%= page.duration %></td>
	<td><%= link_to('Details', :controller => 'page', :action =>'show', :num => page.id) %></td>
  </tr>
<% end %>
</table><br>


<%= link_to "Back", index_sites_path %> 